name: Deploy to Dokploy

on:
  push:
    branches:
      - main  # Chạy khi có push vào nhánh main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Airflow
        run: pip install apache-airflow
      - name: Validation DAGs (Syntax check)
        run: |
          python -m compileall dags/
          # Khởi tạo database tạm thời để Airflow 3 có thể kiểm tra lỗi
          export AIRFLOW__CORE__LOAD_EXAMPLES=False
          airflow db migrate
          airflow dags list-import-errors

  deploy:
    needs: test # Chỉ deploy nếu bước test thành công
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Dokploy Webhook
        run: |
          curl -X POST "${{ secrets.DOKPLOY_WEBHOOK }}"
